export const APP_CONFIG = {
  BOOKING: {
    MAX_ADVANCE_DAYS: 30,
    MIN_ADVANCE_HOURS: 2,
    CANCELLATION_WINDOW_HOURS: 2,
    SLOT_DURATION_MINUTES: 30,
    SLOTS_PER_DAY: 16,
    MAX_ADD_ONS: 5,
  },
  PAYMENT: {
    MIN_ADVANCE_PERCENTAGE: 20,
    MAX_ADVANCE_PERCENTAGE: 50,
    DEFAULT_ADVANCE_PERCENTAGE: 30,
    DELIVERY_FEE_COD: 40,
    FREE_DELIVERY_THRESHOLD: 500,
    PAYMENT_TIMEOUT_SECONDS: 300,
  },
  VALIDATION: {
    MIN_PHONE_LENGTH: 10,
    MAX_PHONE_LENGTH: 10,
    OTP_LENGTH: 6,
    OTP_EXPIRY_MINUTES: 10,
    MIN_PASSWORD_LENGTH: 8,
    MAX_NAME_LENGTH: 50,
    MAX_ADDRESS_LENGTH: 200,
    MAX_NOTES_LENGTH: 500,
  },
  COUPON: {
    MIN_CODE_LENGTH: 4,
    MAX_CODE_LENGTH: 20,
    MAX_PERCENTAGE: 100,
  },
  UPLOAD: {
    MAX_FILE_SIZE_MB: 5,
    ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
    MAX_IMAGES_PER_PRODUCT: 5,
  },
} as const;
