import type { AdminService, AdminProduct, AdminCategory } from '@/types/admin';

// Mock Services
export const mockServices: AdminService[] = [
  {
    id: 'SRV001',
    name: 'Premium Car Wash',
    description: 'Complete exterior wash with foam and wax',
    category: 'Car Wash',
    price: 599,
    duration: 45,
    status: 'active',
    totalBookings: 342,
    rating: 4.8,
    createdAt: '2023-01-15',
  },
  {
    id: 'SRV002',
    name: 'Interior Detailing',
    description: 'Deep cleaning of car interiors including seats and dashboard',
    category: 'Detailing',
    price: 899,
    duration: 90,
    status: 'active',
    totalBookings: 256,
    rating: 4.7,
    createdAt: '2023-01-20',
  },
  {
    id: 'SRV003',
    name: 'Full Service',
    description: 'Complete car wash and detailing package',
    category: 'Premium',
    price: 1299,
    duration: 120,
    status: 'active',
    totalBookings: 189,
    rating: 4.9,
    createdAt: '2023-02-01',
  },
  {
    id: 'SRV004',
    name: 'Express Wash',
    description: 'Quick exterior wash for busy schedules',
    category: 'Car Wash',
    price: 399,
    duration: 30,
    status: 'active',
    totalBookings: 428,
    rating: 4.5,
    createdAt: '2023-02-10',
  },
  {
    id: 'SRV005',
    name: 'Bike Wash',
    description: 'Complete bike cleaning service',
    category: 'Bike Wash',
    price: 199,
    duration: 25,
    status: 'active',
    totalBookings: 312,
    rating: 4.6,
    createdAt: '2023-03-01',
  },
];

// Mock Products
export const mockProducts: AdminProduct[] = [
  {
    id: 'PROD001',
    name: 'Car Shampoo',
    description: 'Premium pH balanced car shampoo for gentle cleaning',
    category: 'Cleaning',
    categoryId: 'CAT001',
    price: 299,
    stock: 45,
    status: 'active',
    rating: 4.5,
    createdAt: '2023-01-15',
    specifications: {
      volume: '500ml',
      type: 'Liquid',
      fragrance: 'Lemon',
    },
  },
  {
    id: 'PROD002',
    name: 'Microfiber Cloth',
    description: 'Soft microfiber cloth for scratch-free cleaning',
    category: 'Accessories',
    categoryId: 'CAT002',
    price: 199,
    stock: 120,
    status: 'active',
    rating: 4.7,
    createdAt: '2023-01-20',
    specifications: {
      size: '40x40cm',
      material: 'Microfiber',
      color: 'Blue',
    },
  },
  {
    id: 'PROD003',
    name: 'Tire Cleaner',
    description: 'Powerful tire and rim cleaner',
    category: 'Cleaning',
    categoryId: 'CAT001',
    price: 399,
    stock: 32,
    status: 'active',
    rating: 4.6,
    createdAt: '2023-02-01',
    specifications: {
      volume: '750ml',
      type: 'Spray',
    },
  },
  {
    id: 'PROD004',
    name: 'Dashboard Polish',
    description: 'UV protection dashboard polish',
    category: 'Polish',
    categoryId: 'CAT003',
    price: 249,
    stock: 58,
    status: 'active',
    rating: 4.4,
    createdAt: '2023-02-10',
    specifications: {
      volume: '250ml',
      finish: 'Matte',
    },
  },
  {
    id: 'PROD005',
    name: 'Wax Polish',
    description: 'Premium carnauba wax for long-lasting shine',
    category: 'Polish',
    categoryId: 'CAT003',
    price: 599,
    stock: 15,
    status: 'active',
    rating: 4.8,
    createdAt: '2023-03-01',
    specifications: {
      volume: '300ml',
      type: 'Paste',
      protection: '3 months',
    },
  },
  {
    id: 'PROD006',
    name: 'Glass Cleaner',
    description: 'Streak-free glass cleaner',
    category: 'Cleaning',
    categoryId: 'CAT001',
    price: 179,
    stock: 8,
    status: 'out_of_stock',
    rating: 4.3,
    createdAt: '2023-03-15',
    specifications: {
      volume: '500ml',
      type: 'Spray',
    },
  },
];

// Mock Categories
export const mockCategories: AdminCategory[] = [
  {
    id: 'CAT001',
    name: 'Cleaning Products',
    type: 'product',
    description: 'Car cleaning and washing products',
    status: 'active',
    itemCount: 3,
    createdAt: '2023-01-10',
  },
  {
    id: 'CAT002',
    name: 'Accessories',
    type: 'product',
    description: 'Car care accessories and tools',
    status: 'active',
    itemCount: 1,
    createdAt: '2023-01-10',
  },
  {
    id: 'CAT003',
    name: 'Polish & Wax',
    type: 'product',
    description: 'Car polish and wax products',
    status: 'active',
    itemCount: 2,
    createdAt: '2023-01-10',
  },
  {
    id: 'CAT004',
    name: 'Car Wash Services',
    type: 'service',
    description: 'Professional car washing services',
    status: 'active',
    itemCount: 2,
    createdAt: '2023-01-10',
  },
  {
    id: 'CAT005',
    name: 'Detailing Services',
    type: 'service',
    description: 'Professional car detailing services',
    status: 'active',
    itemCount: 2,
    createdAt: '2023-01-10',
  },
  {
    id: 'CAT006',
    name: 'Bike Services',
    type: 'service',
    description: 'Bike washing and maintenance services',
    status: 'active',
    itemCount: 1,
    createdAt: '2023-01-10',
  },
];
